export const DEFINITIONS = {
  "1": "Scope 1 emissions are direct greenhouse (GHG) emissions that occur from sources that are controlled or owned by an organization\
    (e.g., emissions associated with fuel combustion in boilers, furnaces, vehicles)",
  "2": "Scope 2 emissions are indirect GHG emissions associated with the purchase of electricity, steam, heat, or cooling",
  'Purchased goods and services': `Measure emissions of extraction, production, and transportation of goods and services purchased or acquired by your company`,
  'Capital goods': `Measure the emissions of the extraction, production, and transportation of capital goods purchased or acquired by your company`,
  'Fuel and energy related activities': "Measure energy related activites which are not already covered by Scopes 1 & 2",
  'Upstream transportation and distribution':"Measure emissions - generated by you and tier 1 suppliers - caused by the transportation and distribution of products purchased by your company",
  'Waste generated in operations': "Measure emissions of disposal and treatment of waste generated (in facilities not owned by your company)",
  "Business travel": "Measure emissions caused by the transportation of employees for business-related activites. (In vehicles not owned by your company)",
  'Employee commuting': "Measure emissions caused by the transportation of employees between their homes and their worksites. (In vehicles not owned by your company)",
  "Upstream leased assets": "Measure emissions from the operation of assets leased by your company, not included in Scopes 1 & 2",
  "Downstream transportation and distribution": "Measure emissions caused by transportation and distribution of products sold, between company operations and the end consumer",
  "Processing of sold products": "Measure emissions caused by the processing of intermediate products sold by downstream companies (e.g., manufacturers)",
  "Use of sold products": "Measure emissions caused by the end use of sold products",
  "End-of-life treatment of sold products": "Measure emissions caused by Waste disposal and treatment of sold products",
  "Downstream leased assets": "Measure emissions the operation of assets owned and leased to other entities",
  "Franchises": "Measure the emissions of franchises operations not included in Scopes 1 & 2",
  "Investments": "Measure the emissions of investments operations not included in Scopes 1 & 2"
}

export const emailRegex = RegExp("[a-z0-9]+@[a-z]+\.[a-z]{2,3}");